"""add profile_photo_url to users

Revision ID: 0f285d0d3c43
Revises: 64c4a5f1d2da
Create Date: 2026-08-08 00:17:49.568381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f285d0d3c43'
down_revision: Union[str, Sequence[str], None] = '64c4a5f1d2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'complaint_responses', 'users', ['responder_id'], ['id'])
    op.create_foreign_key(None, 'complaints', 'users', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'maintenance_assignments', 'users', ['assigned_by'], ['id'])
    op.create_foreign_key(None, 'maintenance_assignments', 'users', ['staff_id'], ['id'])
    op.create_foreign_key(None, 'maintenance_requests', 'users', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'notification_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'properties', 'users', ['landlord_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rent_payments', 'users', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'rental_agreements', 'users', ['landlord_id'], ['id'])
    op.create_foreign_key(None, 'rental_agreements', 'users', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'tenant_assignments', 'users', ['assigned_by'], ['id'])
    op.create_foreign_key(None, 'tenant_assignments', 'users', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tenant_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('profile_photo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo_url')
    op.drop_constraint(None, 'tenant_profiles', type_='foreignkey')
    op.drop_constraint(None, 'tenant_assignments', type_='foreignkey')
    op.drop_constraint(None, 'tenant_assignments', type_='foreignkey')
    op.drop_constraint(None, 'rental_agreements', type_='foreignkey')
    op.drop_constraint(None, 'rental_agreements', type_='foreignkey')
    op.drop_constraint(None, 'rent_payments', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notification_preferences', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_requests', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_assignments', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_assignments', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaint_responses', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    # ### end Alembic commands ###
