"""add tenant_accepted_at to rental_agreements

Revision ID: 18a66ec86a72
Revises: 8b11194a9590
Create Date: 2026-07-20 01:49:53.813593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a66ec86a72'
down_revision: Union[str, Sequence[str], None] = '8b11194a9590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_agreements', sa.Column('tenant_accepted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_agreements', 'tenant_accepted_at')
    # ### end Alembic commands ###
