"""Add image_url to properties

Revision ID: 29ae30714499
Revises: 1ae4db7ad7bc
Create Date: 2026-06-26 14:05:49.254811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ae30714499'
down_revision: Union[str, Sequence[str], None] = '1ae4db7ad7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('image_url', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_refresh_tokens_user_id_revoked'), table_name='refresh_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_refresh_tokens_user_id_revoked'), 'refresh_tokens', ['user_id', 'revoked'], unique=False)
    op.drop_column('properties', 'image_url')
    # ### end Alembic commands ###
