"""recreate users with correct columns

Revision ID: 744004a0c95c
Revises: 4821117015c2
Create Date: 2026-06-19 01:19:02.868795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744004a0c95c'
down_revision: Union[str, Sequence[str], None] = '4821117015c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'landlord', 'tenant', 'maintenance_staff', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'complaint_responses', 'users', ['responder_id'], ['id'])
    op.create_foreign_key(None, 'complaints', 'users', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'maintenance_assignments', 'users', ['staff_id'], ['id'])
    op.create_foreign_key(None, 'maintenance_assignments', 'users', ['assigned_by'], ['id'])
    op.create_foreign_key(None, 'maintenance_requests', 'users', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'notification_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'properties', 'users', ['landlord_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rent_payments', 'users', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'rental_agreements', 'users', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'rental_agreements', 'users', ['landlord_id'], ['id'])
    op.create_foreign_key(None, 'tenant_assignments', 'users', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tenant_assignments', 'users', ['assigned_by'], ['id'])
    op.create_foreign_key(None, 'tenant_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_profiles', type_='foreignkey')
    op.drop_constraint(None, 'tenant_assignments', type_='foreignkey')
    op.drop_constraint(None, 'tenant_assignments', type_='foreignkey')
    op.drop_constraint(None, 'rental_agreements', type_='foreignkey')
    op.drop_constraint(None, 'rental_agreements', type_='foreignkey')
    op.drop_constraint(None, 'rent_payments', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notification_preferences', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_requests', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_assignments', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_assignments', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaint_responses', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
